In [11]:
import  numpy as np
print(np.__version__)

1.23.5


In [25]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype = 'int64') #default ma chai 32 bit use garxa
print(a)
print(type(a))
print(a.shape)
print(a.size)
print(a.nbytes) #memory kati leko xa 
print(a.ndim)
print(a.dtype)

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
(9,)
9
72
1
int64


In [27]:
x = ([1, 2, 3, 4, 5, 6]) #regular list
y= ([7, 8, 9, 10, 11,12])
print(x + y)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [31]:
x = np.array([1, 2, 3, 4, 5, 6]) #numpy list
y= np.array([7, 8, 9, 10, 11,12])
print(x + y)
print(x - y)
print(x * y)

[ 8 10 12 14 16 18]
[-6 -6 -6 -6 -6 -6]
[ 7 16 27 40 55 72]
