In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

[1 2 3 4 5 6]


In [4]:
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
print(b.shape)
print(b.size)
print(b.nbytes)

(2, 3)
6
24


In [9]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
print(x.shape)
print(x.size)

(3, 3)
9


In [13]:
print(x[2][2])
print(x[1][2])

9
6


In [18]:
print(x.sum())
print(x.sum(axis=0))
print(x.sum(axis=1))

45
[12 15 18]
[ 6 15 24]


# another one

In [19]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [22]:
print(a[0,:])#prints only row in this pattern
print(a[1,:])

[1 2 3]
[4 5 6]


In [28]:
print(a[:,0]) #prints colums in this pattern
print(a[:,2])

[1 4 7]
[3 6 9]


In [29]:
x = np.arange(15)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [30]:
x= np.zeros(5)
print(x)

[0. 0. 0. 0. 0.]


In [36]:
x = np.ones(4)
print(x)

[1. 1. 1. 1.]


In [38]:
x = np.full([2,3],9)
print(x)

[[9 9 9]
 [9 9 9]]


In [45]:
x = np.identity(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [46]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
b = np.array([10, 11,12, 13, 14, 15, 16, 17,18])
print(a)
print(b)

[1 2 3 4 5 6 7 8 9]
[10 11 12 13 14 15 16 17 18]


In [48]:
print(a[1:7:2]) #slicing garya

[2 4 6]


In [49]:
print(a[::])

[1 2 3 4 5 6 7 8 9]


In [50]:
c = np.hstack([a,b])
print(c)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [51]:
c = np.vstack([a,b])
print(c)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]]


In [58]:
a = np.genfromtxt('data.txt', delimiter=',')
print(a)

[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]
