In [6]:
import numpy as np
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
c = a + b
print(f"{a}\n{b}")
print(c)

[1 2 3 4]
[5 6 7 8]
[ 6  8 10 12]


In [7]:
print(type(c))

<class 'numpy.ndarray'>


In [8]:
print(c.size)

4


In [9]:
print(c.shape)

(4,)


In [11]:
print(c.sum())

36


# Practice sets

In [12]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [14]:
print(x.sum())

45


In [15]:
print(x.min())

1


In [16]:
print(x.max())

9


In [17]:
print(x.mean())

5.0


In [18]:
print(x.std())

2.581988897471611


In [19]:
print(x[2]) #Support indexing

3


In [20]:
print(x[1:5]) #Support slicing

[2 3 4 5]


In [21]:
x[1:5]

array([2, 3, 4, 5])

In [23]:
x = x * a[1]
print(x)

[ 4  8 12 16 20 24 28 32 36]


In [24]:
c = np.array([5, 6, 7])
d = np.array([9, 10, 11])

In [25]:
c[1]

6

In [26]:
print(d*c[1])

[54 60 66]


In [27]:
x = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(x)

[1 2 3 4 5 6 7 8 9]


In [30]:
x = x.reshape(3,3)

In [31]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
